server:
  port: 8091
  address: 0.0.0.0

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_platform
    username: fitness_user
    password: fitness_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Temporarily disable security
  security:
    user:
      name: admin
      password: admin123

  jwt:
    secret: mySecretKey12345678901234567890123456789012345678901234567890
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days